server:
  error:
    include-message: always
  port: ${PORT_USER_API:8000}
spring:
  application:
    name: user-api
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}