spring:
  application:
    name: payroll-api
  aop:
    proxy-target-class: false
server:
  port: ${PORT_PAYROLL_API:8200}
feign:
  httpclient:
    enabled: true
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
